force-app/main/default/objects/FD_Airport__c/FD_Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FD_Airport__c/fields/FD_Latitude__c.field-meta.xml
<CustomField>
    <fullName>FD_Latitude__c</fullName>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FD_Airport__c/fields/FD_Longitude__c.field-meta.xml
<CustomField>
    <fullName>FD_Longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FD_FlightDistanceController.cls
/**
 * @author Mykola Kanunnikov
 * @date 28 March, 2024
 * @description Controller for FlightDistance LWC
 */
public with sharing class FD_FlightDistanceController {

    /**
     * @author Mykola Kanunnikov
     * @date 28 March, 2024
     * @description getDistanceKm between airports
     * @param  departureAirportId 
     * @param  arrivalAirportId 
     * @return       return approx. distance in km
     */
    @AuraEnabled
    public static Integer getDistanceKm(Id departureAirportId, Id arrivalAirportId) {
        FD_LocationUtils.DistanceParameter param = new FD_LocationUtils.DistanceParameter();
        param.unit = 'km';
        try {
            List<FD_Airport__c> airports = [SELECT FD_Latitude__c, FD_Longitude__c
                                         FROM FD_Airport__c
                                         WHERE Id IN :new List<String> {departureAirportId, arrivalAirportId}
                                         WITH USER_MODE];

            for (FD_Airport__c airport : airports) {
                if (airport.Id == departureAirportId) {
                    param.departureLatitude = airport.FD_Latitude__c;
                    param.departurelongitude = airport.FD_Longitude__c;
                } else {
                    param.arrivalLatitude = airport.FD_Latitude__c;
                    param.arrivalLongitude = airport.FD_Longitude__c;
                }
            }
            return Math.round(FD_LocationUtils.getDistance(param));
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}