force-app/main/default/objects/FD_Airport__c/FD_Airport__c.object-meta.xml
<CustomObject>
    <label>Airport</label>
    <nameField>
        <label>Airport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Airports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FD_Airport__c/fields/FD_Latitude__c.field-meta.xml
<CustomField>
    <fullName>FD_Latitude__c</fullName>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FD_Airport__c/fields/FD_Longitude__c.field-meta.xml
<CustomField>
    <fullName>FD_Longitude__c</fullName>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>14</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FD_FlightDistanceController_Test.cls
@isTest
private with sharing class FD_FlightDistanceController_Test {

    @isTest
    static void testGetDistanceKm() {
        System.runAs(FD_TestDataFactory.createFlightDistanceUser()) {
            FD_Airport__c departureAirport = new FD_Airport__c(Name = 'BCN', FD_Latitude__c = 41.2971, FD_Longitude__c = 2.07846);
            FD_Airport__c arrivalAirport = new FD_Airport__c(Name = 'LHR', FD_Latitude__c = 51.4706, FD_Longitude__c = -0.461941);
            insert new List<FD_Airport__c> {departureAirport, arrivalAirport};

            Test.startTest();
                Integer distance = FD_FlightDistanceController.getDistanceKm(departureAirport.Id, arrivalAirport.Id);
            Test.stopTest();

            Assert.areEqual(1148, distance, 'Not expected distance');
        }
    }

}